apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
jobs:
  test-actions:
    environment: development
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: docker://adoptopenjdk:17-jdk-hotspot
        shell: sh
        run: |
          ./gradlew clean build

  upload-artifact:
    description: Compile Kotlin and upload JAR to JFrog
    needs: compile
    steps:
      - name: Checkout sources
        uses: docker://adoptopenjdk:17-jdk-hotspot
        env:
          JFROG_URL: https://alleyoopsandbox.jfrog.io
          JFROG_REPO: libs-release-local
          JFROG_ARTIFACT_PATH: kotlin-artifacts/your-app-${{ github.sha }}.jar
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
        shell: sh
        run: |
          # Install jfrog CLI
          curl -fL https://getcli.jfrog.io | sh
          ./jfrog rt c default --url=$JFROG_URL --user=$JFROG_USERNAME --password=$JFROG_PASSWORD
          # Upload the JAR, versioned with commit SHA or tag
          ./jfrog rt u build/libs/*.jar $JFROG_REPO/$JFROG_ARTIFACT_PATH
