apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  # push:
  #   branches:
  #     - "**"
  workflow_dispatch:
    inputs:
      repo_name:
        type: string
        default: t217145/alley-oop-demo-apps
        required: true
        description: Repository Name (do not include the https://github.com/) E.g. t217145/alley-oop-demo-apps
      repo_url:
        type: string
        default: https://github.com/
        description: Repository URL. Default is https://github.com
      # suppose to read the jenkins.properties
      appVersion:
        type: string
        default: "1.0"
        description: Application version, suppose to read the jenkins.properties    
      appName:
        type: string
        default: "demo-apps"
        description: Application name, suppose to read the jenkins.properties  

jobs:
  Compile:
    environment: sandbox
    steps:

      - name: Pack
        uses: docker://nginx:latest
        with:
            entrypoint: ''
        run: |
            apt-get update -y && apt-get upgrade -y
            apt-get install wget -y
            apt-get install git -y
            wget https://get.helm.sh/helm-v3.18.3-linux-amd64.tar.gz
            tar -zxvf helm-v3.18.3-linux-amd64.tar.gz
            cd linux-amd64
            git clone https://${{vars.GITHUB_HKJC_ACCOUNT}}:${{secrets.GITHUB_HKJC_TOKEN}}@github.com/${{ inputs.repo_name }}.git apps
            git clone https://${{vars.GITHUB_HKJC_ACCOUNT}}:${{secrets.GITHUB_HKJC_TOKEN}}@github.com/Copilot-POC-Org/alley-oop-cicd-helm.git helm-chart
            cp -f apps/helm/values.yaml helm-chart/values.yaml
            cd helm-chart
            ../helm registry login ${{ vars.JFROG_DOMAIN }} -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.HELM_REPO_TOKEN }}
            ../helm package .
            ../helm push alley-oop-app-0.0.1.tgz oci://${{ vars.JFROG_DOMAIN }}/aop-cicd-helm