apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  # push:
  #   branches:
  #     - "**"
  workflow_dispatch:
    inputs:
      repo_name:
        type: string
        default: t217145/alley-oop-demo-apps
        required: true
        description: Repository Name (do not include the https://github.com/) E.g. t217145/alley-oop-demo-apps
      repo_url:
        type: string
        default: https://github.com/
        description: Repository URL. Default is https://github.com
      # suppose to read the jenkins.properties
      appVersion:
        type: string
        default: "1.0"
        description: Application version, suppose to read the jenkins.properties    
      appName:
        type: string
        default: "app"
        description: Application name, suppose to read the jenkins.properties  

jobs:
  Compile:
    environment: sandbox
    steps:
      - uses: cloudbees-io/checkout@v1
        name: checkout
        with:
          provider: github
          repository: ${{ inputs.repo_name }}
          ref: main
          token: ${{secrets.GITHUB_TOKEN}}
          path: ./app
          github-server-url: ${{ inputs.repo_url }}       
      - uses: docker://gradle:8.14.2-jdk17
        name: compile
        with:
            entrypoint: ''
        run: |
            cd ./app
            gradle clean build -PappVersion=${{ inputs.appVersion }}  -PappName=${{ inputs.appName }}
            pwd
            ls -l
      - name: Upload Dockerfile to JFrog Artifactory
        uses: https://github.com/cloudbees-io/jfrog-artifactory-upload-file@v1
        with:
          url: ${{ vars.JFROG_URL }}
          token: ${{ secrets.JFROG_TOKEN }}
          artifactory-path: ${{ vars.JFROG_REPO }}/${{ inputs.appName }}/${{ inputs.appVersion }}
          file-path: /cloudbees/workspace/app/Dockerfile            
      - name: Upload Jar to JFrog Artifactory
        uses: https://github.com/cloudbees-io/jfrog-artifactory-upload-file@v1
        with:
          url: ${{ vars.JFROG_URL }}
          token: ${{ secrets.JFROG_TOKEN }}
          artifactory-path: ${{ vars.JFROG_REPO }}/${{ inputs.appName }}/${{ inputs.appVersion }}
          file-path: /cloudbees/workspace/app/build/libs/${{ inputs.appName }}-${{ inputs.appVersion }}.jar